### ISSUE TITLE
Invalid php version in composer.json

### ISSUE THREAD

**Issue by drnkwati** [ddrv/mailer#1]
Your composer.json requires php 5.3 but from your source code, i see php 7 coding style.
Please update min php required in json

**Comment by ddrv** [comment]
Please write the mailer version.
Where exactly is the php 7 style found?
I want to provide support for php version 5.3

**Comment by drnkwati** [comment]
Your latest commits has made some changes since i last checked last month.
However, It can be seen in TransportInterface where you type hint callable.
callable type hinting is supportted from php 5.4 not 5.3
Use Closure instead of callable if you want to support php 5.3

**Comment by ddrv** [comment]
Thank you! I fix it in versions [3.1.2](https://github.com/ddrv/mailer/tree/v3.1.2) and [4.0.1](https://github.com/ddrv/mailer/tree/v4.0.1)
